marketplace/main/urls.py
from django.urls import include, path
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'item', views.ItemViewSet)
router.register(r'events', views.EventsViewSet)

app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('like/', views.like, name='like'),
    path('explore/', views.explore, name='explore'),
    path('api/', include(router.urls)),
]

marketplace/marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('', include('main.urls', namespace='main')),
    path('p/', include('profiling.urls', namespace='profiling')),
    path('user/', include('users.urls', namespace='users')),
    path('articles/', include('articles.urls', namespace='articles'))
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/profiling/urls.py
from django.urls import path

from . import views

app_name = 'profiling'

urlpatterns = [
    path('collection/<slug:collection_slug>/', views.collection, name='collection'),
    path('item/<int:id>/', views.item, name='item'),


    path('create/', views.create_options, name='create_options'),
    path('create/single/', views.create_single, name='create_single'),

    path('edit/item<int:id>/', views.edit_item, name='edit_item'),
    path('edit/delete<int:id>/', views.delete_item, name='delete_item')
]

marketplace/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('wallet/', views.wallet, name='wallet'),
    path('<slug:author_username>/', views.profile, name='profile'),

]

marketplace/profiling/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
import requests
from users.models import User


class Item(models.Model):
    title = models.CharField("title", max_length=128, blank=True, null=True)
    image = models.ImageField(upload_to="item_image")
    creator = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="creator",
        verbose_name="creator",
    )
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="owner",
        verbose_name="owner"
    )
    collection = models.ForeignKey(
        "Collection",
        verbose_name="collection",
        related_name="collection",
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    price = models.DecimalField(
        "price_eth", default=0.00, max_digits=4, decimal_places=2
    )
    on_sale = models.BooleanField(default=True)
    likes = models.PositiveIntegerField(verbose_name="likes", default=0)
    creation_date = models.DateTimeField(
        verbose_name="creation date", auto_now_add=True,
    )

    class Meta:
        verbose_name = "Item"
        verbose_name_plural = "Items"

    def price_in_usd(self):
        actual_price = requests.get(
            "https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=USD"
        ).json()["USD"]
        return f"{float(self.price) * actual_price:.2f}"

    def get_absolute_url(self):
        return reverse("profiling:item", args=[self.pk])

    def __str__(self):
        return self.title


class Collection(models.Model):
    title = models.CharField("title", max_length=128)
    description = models.TextField("description", blank=True, null=True)
    slug = models.CharField("slug", max_length=128)
    banner = models.ImageField(
        upload_to="collection_banner",
        default="collections/collection-default.jpg"
    )
    creator = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="collection_creator",
        verbose_name="Collection creator",
    )

    class Meta:
        verbose_name = "Collection"
        verbose_name_plural = "Collections"

    def __str__(self):
        return self.title

marketplace/profiling/forms.py
from django import forms
from .models import Item


class SingleItemCreationForm(forms.ModelForm):
    image = forms.ImageField()
    title = forms.CharField()
    price = forms.DecimalField()

    class Meta:
        model = Item
        fields = ("image", "title", "price")
        exclude = ('creator', 'owner',)


class SingleItemEditForm(forms.ModelForm):
    image = forms.ImageField()
    title = forms.CharField()
    price = forms.DecimalField()

    class Meta:
        model = Item
        fields = ("image", "title", "price")
        exclude = ('creator', 'owner',)

marketplace/profiling/views.py
from django.forms import ValidationError
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.db import transaction

from .forms import (
    SingleItemCreationForm,
    SingleItemEditForm,
)
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import Item, Collection
from main.utils import (
    add_user_action_event,
    add_user_transaction_event,
    check_if_like,
)
from .utils import error_messages


def collection(request, collection_slug):
    template = "profiling/collection.html"
    collection_info = Collection.objects.get(slug=collection_slug)
    collection_items = Item.objects.select_related("creator", "owner").filter(
        collection__slug=collection_slug
    )
    context = {
        "collection": collection_info,
        "items": collection_items,
        "dark": False,
    }
    return render(request, template, context)


def item(request, id):
    template = "profiling/item-details.html"
    item_info = Item.objects.select_related("owner", "creator").get(id=id)
    is_like = check_if_like(request, item_info)
    if request.method == "POST":
        try:
            with transaction.atomic():
                user = request.user
                if user.balance < item_info.price:
                    raise ValidationError("Not enough money on your balance")
                price = item_info.price
                user.balance -= price
                user.save()
                item_info.owner = user
                item_info.save()
                add_user_transaction_event(
                    event="buy item", user=user, number=price, object=item_info
                )
                messages.success(request, "Item successfully yours!")
                return HttpResponseRedirect(
                    reverse("profiling:item", args=[item_info.id])
                )
        except ValidationError as e:
            messages.error(request, str(e))

    context = {"item_info": item_info, "is_like": is_like, "dark": False}
    return render(request, template, context)


@login_required
def create_options(request):
    template = "profiling/create-options.html"
    context = {"dark": True, "subtitle": "Create Collectible"}
    return render(request, template, context)


@login_required
def create_single(request):
    template = "profiling/create-single.html"

    if request.method == "POST":
        form = SingleItemCreationForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.creator = request.user
            item.owner = request.user
            item.save()
            messages.success(request, "Item successfully created!")
            add_user_action_event("create item", request.user, item)
            return HttpResponseRedirect(
                reverse("profiling:item", args=[item.id])
            )
        else:
            error_messages(request, "Image", "Title", "Price")

    else:
        form = SingleItemCreationForm()

    context = {"dark": True, "subtitle": "Create Single Collectible"}
    return render(request, template, context)


@login_required
def edit_item(request, id):
    template = "profiling/edit-item.html"
    item = Item.objects.select_related("owner").get(id=id)

    if request.user != item.owner:
        messages.error(request, "You cannot change an item that is not yours.")
        return HttpResponseRedirect(reverse("main:index"))

    if request.method == "POST":
        form = SingleItemEditForm(
            data=request.POST, instance=item, files=request.FILES
        )
        if form.is_valid():
            form.save()
            add_user_action_event("edit item", request.user, item)
            messages.success(request, "Item successfully edited!")
            return redirect(request.META["HTTP_REFERER"])
        else:
            error_messages(request, "Title", "Price")
    else:
        form = SingleItemEditForm()

    context = {"dark": True, "item": item, "subtitle": "Edit Item"}
    return render(request, template, context)


@login_required
def delete_item(request, id):
    item = Item.objects.get(id=id)
    item.delete()
    return HttpResponseRedirect(
        reverse("users:profile", args=[request.user.username])
    )

marketplace/templates/profiling/create-options.html
{% extends "base.html" %}
{% load static %}
{% load posts_tags %}

{% block title %}
Gigaland - Articles
{% endblock %}

{% block content %}
            <!-- section begin -->
            {% include "includes/subheader.html" %}
            <!-- section close -->
            <section aria-label="section">
                <div class="container">
                    <div class="row wow fadeIn">
                        <div class="col-md-6 offset-md-3">
                            <p>Choose "Single" if you want your collectible to be one of a kind or "Multiple" if you want to sell one collectible times</p>
                            <a href="{% url "profiling:create_single" %}" class="opt-create">
                                <img src="{% static "images/misc/coll-single.png" %}" alt="">
                                <h3>Single</h3>
                            </a>
                            <a href="create-multiple.html" class="opt-create">
                                <img src="{% static "images/misc/coll-multiple.png" %}" alt="">
                                <h3>Multiple</h3>
                            </a>
                        </div>                             
                    </div>
                </div>
            </section>
{% endblock content %}

marketplace/templates/profiling/create-single.html
{% extends "base.html" %}
{% load static %}
{% load posts_tags %}

{% block title %}
Gigaland - Articles
{% endblock %}

{% block content %}
            
            <!-- section begin -->
            {% include "includes/subheader.html" %}
            <!-- section close -->
            

            <!-- section begin -->
            <section aria-label="section">
                <div class="container">
                    <div class="row wow fadeIn">
                        <div class="col-lg-7 offset-lg-1">
                            <form action="" id="form-create-item" class="form-border" method="post" enctype="multipart/form-data">
                                {% csrf_token %}

                                {% include "includes/messages.html" %}

                                <div class="field-set">
                                    <h5>Upload file</h5>

                                    <div class="d-create-file">
                                        <p id="file_name">PNG, JPG, GIF, WEBP or MP4. Max 200mb.</p>
                                        <label for="id_image"><input type="button" id="get_file" class="btn-main" value="Browse" onclick="triggerFileInput()"></label>
                                        <input type="file" id="id_image" name="image" style="display: none;" accept="image/*" onchange="previewImage()">
                                    </div>

                                    <div class="spacer-40"></div>

                                    <h5>Title</h5>
                                    <input type="text" name="title" id="id_title" class="form-control" placeholder="e.g. 'Crypto Funk" />

                                    <div class="spacer-20"></div>

                                                <h5>Price</h5>
                                                <input type="text" name="price" id="id_price" class="form-control" placeholder="enter price for one item (ETH)" />
                                                {% if form.price.errors %}
                                                <span style="font-size: 95%; font-style: italic; color: red; opacity: 0.85;"><div style="margin: -16px;">{{ form.price.errors }}</div></span>
                                                {% endif %}


                                    <div class="spacer-20"></div>

                                    <h5>Choose collection</h5>
                                    <p class="p-info">This is the collection where your item will appear.</p>

                                    <div id="item_collection" class="dropdown fullwidth mb20">
                                        <a href="#" class="btn-selector">Select Collection</a>
                                        <ul>
                                            <li><span>Abstraction</span></li>
                                            <li><span>Patternlicious</span></li>
                                            <li><span>Skecthify</span></li>
                                            <li><span>Cartoonism</span></li>
                                            <li><span>Virtuland</span></li>
                                            <li><span>Papercut</span></li>
                                        </ul>
                                    </div>

                                    <div class="spacer-20"></div>

                                    

                                    <h5>Description</h5>
                                    <textarea data-autoresize name="description" id="id_description" class="form-control" placeholder="e.g. 'This is very limited item'"></textarea>


                                    <div class="spacer-single"></div>

                                    <input type="submit" id="submit" class="btn-main" value="Create Item">
                                    <div class="spacer-single"></div>
                                </div>
                            </form>
                        </div>

                        <div class="col-lg-3 col-sm-6 col-xs-12">
                                <h5>Preview item</h5>
                                <div class="nft__item">
                                    <div class="de_countdown" data-year="2022" data-month="4" data-day="16" data-hour="8"></div>
                                    <div class="author_list_pp">
                                        <a href="#">                                    
                                            <img class="lazy" src="{{ user.avatar.url }}" alt="">
                                            <i class="fa fa-check"></i>
                                        </a>
                                    </div>
                                    <div class="nft__item_wrap">
                                            <img src="{% static "images/items/default_item.jpg" %}" id="get_file_2" class="lazy nft__item_preview" alt="">
                                    </div>
                                    <div class="nft__item_info">
                                        <a href="#">
                                            <h4>Wonderful picture</h4>
                                        </a>
                                        <div class="nft__item_click">
                                        <span></span>
                                    </div>
                                    <div class="nft__item_price">
                                            0.08 ETH<span>1/20</span>
                                        </div>
                                        <div class="nft__item_action">
                                            <a href="#">Place a bid</a>
                                        </div>
                                        <div class="nft__item_like">
                                            <i class="fa fa-heart"></i><span>50</span>
                                        </div>                            
                                    </div> 
                                </div>
                            </div>                                         
                    </div>
                </div>
            </section>

{% endblock content %}

marketplace/templates/profiling/edit-item.html
{% extends "base.html" %}
{% load static %}
{% load posts_tags %}

{% block title %}
Gigaland - Edit item {{ item.title }}
{% endblock %}

{% block content %}
            
            <!-- section begin -->
            {% include "includes/subheader.html" %}
            <!-- section close -->
            
            <!-- section begin -->
            <section aria-label="section">
                <div class="container">
                    <div class="row wow fadeIn">
                        <div class="col-lg-7 offset-lg-1">
                            <form action="" id="form-create-item" class="form-border" method="post" enctype="multipart/form-data">
                                {% csrf_token %}

                                {% include "includes/messages.html" %}

                                <div class="field-set">
                                    <h5>Upload file</h5>

                                    <div class="d-create-file">
                                        <p id="file_name">PNG, JPG, GIF, WEBP or MP4. Max 200mb.</p>
                                        <label for="id_image"><input type="button" id="get_file" class="btn-main" value="Browse" onclick="triggerFileInput()"></label>
                                        <input type="file" id="id_image" name="image" style="display: none;" accept="image/*" onchange="previewImage()">
                                    </div>

                                    <div class="spacer-40"></div>

                                    {% comment %} <h5>Select method</h5> {% endcomment %}
                                    <div class="de_tab tab_methods">
                                        {% comment %} <ul class="de_nav">
                                            <li class="active"><span><i class="fa fa-tag"></i>Fixed price</span>
                                            </li>
                                            <li><span><i class="fa fa-hourglass-1"></i>Timed auction</span>
                                            </li>
                                            <li><span><i class="fa fa-users"></i>Open for bids</span>
                                            </li>
                                        </ul> {% endcomment %}

                                        <div class="de_tab_content">

                                            <div id="tab_opt_1">


                                                <h5>Title</h5>
                                                <input type="text" name="title" id="id_title" class="form-control" placeholder="e.g. 'Crypto Funk" value="{{ item.title }}"/>

                                                <h5>Price</h5>
                                                <input type="text" name="price" id="id_price" class="form-control" placeholder="enter price for one item (ETH)" value="{{ item.price }}"/>
                                                {% if form.price.errors %}
                                                <span style="font-size: 95%; font-style: italic; color: red; opacity: 0.85;"><div style="margin: -16px;">{{ form.price.errors }}</div></span>
                                                {% endif %}
                                            </div>

                                            <div id="tab_opt_2">
                                                <h5>Minimum bid</h5>
                                                <input type="text" name="item_price_bid" id="item_price_bid" class="form-control" placeholder="enter minimum bid" />

                                                <div class="spacer-20"></div>

                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <h5>Starting date</h5>
                                                        <input type="date" name="bid_starting_date" id="bid_starting_date" class="form-control" min="1997-01-01" />
                                                    </div>
                                                    <div class="col-md-6">
                                                        <h5>Expiration date</h5>
                                                        <input type="date" name="bid_expiration_date" id="bid_expiration_date" class="form-control" />
                                                    </div>
                                                </div>
                                            </div>

                                            <div id="tab_opt_3">
                                            </div>

                                        </div>

                                    </div>

                                    <div class="spacer-20"></div>


                                    <h5>Choose collection</h5>
                                    <p class="p-info">This is the collection where your item will appear.</p>

                                    <div id="item_collection" class="dropdown fullwidth mb20">
                                        <a href="#" class="btn-selector">Select Collection</a>
                                        <ul>
                                            <li><span>Abstraction</span></li>
                                            <li><span>Patternlicious</span></li>
                                            <li><span>Skecthify</span></li>
                                            <li><span>Cartoonism</span></li>
                                            <li><span>Virtuland</span></li>
                                            <li><span>Papercut</span></li>
                                        </ul>
                                    </div>



                                    <div class="spacer-20"></div>

                                    <div class="spacer-single"></div>

                                    <input type="submit" id="submit" class="btn-main" value="Save changes">

                                    <a href="#" class="btn-main" data-bs-toggle="modal" data-bs-target="#delete" style="float: right; right: 0px; background: #de1c10;">
                                         Delete item
                                      </a>

                                    <!-- delete -->
                                    <div class="modal fade" id="delete" tabindex="-1" aria-labelledby="buy_now" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered de-modal">
                                          <div class="modal-content">
                                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                            <div class="modal-body">
                                              <div class="p-3 form-border" style="text-align: center">
                                                  <h3>Warning</h3>
                                                  You are about to delete <b>{{ item.title }}</b>
                                                  <div class="spacer-single"></div>
                                                  <a href="{% url "profiling:delete_item" item.id %}" class="btn-main btn-fullwidth" style="background: #de1c10;">Delete</a>
                                              </div>
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                    <!-- delete -->

                                    <div class="spacer-single"></div>
                                </div>
                            </form>
                        </div>

                        <div class="col-lg-3 col-sm-6 col-xs-12">
                                <h5>Preview item</h5>
                                <div class="nft__item">
                                    <div class="de_countdown" data-year="2022" data-month="4" data-day="16" data-hour="8"></div>
                                    <div class="author_list_pp">
                                        <a href="#">                                    
                                            <img class="lazy" src="{{ user.avatar.url }}" alt="">
                                            <i class="fa fa-check"></i>
                                        </a>
                                    </div>
                                    <div class="nft__item_wrap">
                                            <img src="{{ item.image.url }}" id="get_file_2" class="lazy nft__item_preview" alt="">
                                    </div>
                                    <div class="nft__item_info">
                                        <a href="#">
                                            <h4>{{ item.title }}</h4>
                                        </a>
                                        <div class="nft__item_click">
                                        <span></span>
                                    </div>
                                    <div class="nft__item_price">
                                            {{ item.price }} ETH<span>1/20</span>
                                        </div>
                                        <div class="nft__item_action">
                                            <a href="#">Place a bid</a>
                                        </div>
                                        <div class="nft__item_like">
                                            <i class="fa fa-heart"></i><span>50</span>
                                        </div>                            
                                    </div> 
                                </div>
                            </div>                                         
                    </div>
                </div>
            </section>

{% endblock content %}