marketplace/articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.articles, name='articles'),
    path('search/', views.articles, name='search'),
    path('<int:article_id>/', views.article_detail, name='article_detail'),
    path('write/', views.write_article, name='write_article'),
]

marketplace/main/urls.py
from django.urls import include, path
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'item', views.ItemViewSet)
router.register(r'events', views.EventsViewSet)

app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('like/', views.like, name='like'),
    path('explore/', views.explore, name='explore'),
    path('api/', include(router.urls)),
]

marketplace/marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('', include('main.urls', namespace='main')),
    path('p/', include('profiling.urls', namespace='profiling')),
    path('user/', include('users.urls', namespace='users')),
    path('articles/', include('articles.urls', namespace='articles'))
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/profiling/urls.py
from django.urls import path

from . import views

app_name = 'profiling'

urlpatterns = [
    path('collection/<slug:collection_slug>/', views.collection, name='collection'),
    path('item/<int:id>/', views.item, name='item'),


    path('create/', views.create_options, name='create_options'),
    path('create/single/', views.create_single, name='create_single'),

    path('edit/item<int:id>/', views.edit_item, name='edit_item'),
    path('edit/delete<int:id>/', views.delete_item, name='delete_item')
]

marketplace/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('wallet/', views.wallet, name='wallet'),
    path('<slug:author_username>/', views.profile, name='profile'),

]

marketplace/templates/includes/footer.html
{% load static %}
<footer class="footer-light">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-6 col-xs-1">
                <div class="widget">
                    <h5>Marketplace</h5>
                    <ul>
                        <li><a href="#">All NFTs</a></li>
                        <li><a href="#">Art</a></li>
                        <li><a href="#">Music</a></li>
                        <li><a href="#">Domain Names</a></li>
                        <li><a href="#">Virtual World</a></li>
                        <li><a href="#">Collectibles</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-1">
                <div class="widget">
                    <h5>Resources</h5>
                    <ul>
                        <li><a href="#">Help Center</a></li>
                        <li><a href="#">Partners</a></li>
                        <li><a href="#">Suggestions</a></li>
                        <li><a href="#">Discord</a></li>
                        <li><a href="#">Docs</a></li>
                        <li><a href="#">Newsletter</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-1">
                <div class="widget">
                    <h5>Community</h5>
                    <ul>
                        <li><a href="#">Community</a></li>
                        <li><a href="#">Documentation</a></li>
                        <li><a href="#">Brand Assets</a></li>
                        <li><a href="#">Blog</a></li>
                        <li><a href="#">Forum</a></li>
                        <li><a href="#">Mailing List</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-1">
                <div class="widget">
                    <h5>Newsletter</h5>
                    <p>Signup for our newsletter to get the latest news in your inbox.</p>
                    <form action="blank.php" class="row form-dark" id="form_subscribe" method="post" name="form_subscribe">
                        <div class="col text-center">
                            <input class="form-control" id="txt_subscribe" name="txt_subscribe" placeholder="enter your email" type="text" /> <a href="#" id="btn-subscribe"><i class="arrow_right bg-color-secondary"></i></a>
                            <div class="clearfix"></div>
                        </div>
                    </form>
                    <div class="spacer-10"></div>
                    <small>Your email is safe with us. We don't spam.</small>
                </div>
            </div>
        </div>
    </div>
    <div class="subfooter">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="de-flex">
                        <div class="de-flex-col">
                            <a href="index.html">
                                <img alt="" class="f-logo" src="{% static "images/logo.png" %}" /><span class="copy">&copy; Template by FAWAZ</span>
                            </a>
                        </div>
                        <div class="de-flex-col">
                            <div class="social-icons">
                                <a href="#"><i class="fa fa-facebook fa-lg"></i></a>
                                <a href="#"><i class="fa fa-twitter fa-lg"></i></a>
                                <a href="#"><i class="fa fa-linkedin fa-lg"></i></a>
                                <a href="#"><i class="fa fa-pinterest fa-lg"></i></a>
                                <a href="#"><i class="fa fa-rss fa-lg"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

marketplace/templates/includes/header.html
{% load static %}
{% if request.path == '/' %}
<header class="transparent header-light scroll-light">
{% elif dark  %}
<header class="transparent">
{% else %}
<header class="header-light scroll-light">
{% endif %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="de-flex sm-pt10">
                <div class="de-flex-col">
                    <div class="de-flex-col">
                        <!-- logo begin -->
                        <div id="logo">
                                <a href="{% url "main:index" %}">
                                    <img alt="" class="logo" src="{% static "images/logo-light.png" %}" />
                                    <img alt="" class="logo-2" src="{% static "images/logo.png" %}" />
                                </a>
                            </div>
                            <!-- logo close -->
                        </div>
                        <div class="de-flex-col">
                            <form action="" method="get" name="form_quick_search" role="search">
                            <input id="quick_search" class="xs-hide" name="q" placeholder="search item here..." type="text" />
                            </form>
                        </div>
                    </div>
                    <div class="de-flex-col header-col-mid">
                        <!-- mainmenu begin -->
                        <ul id="mainmenu">
                            <li>
                                <a href="{% url "main:index" %}">Home<span></span></a>
                                <ul>
                                    <li><a href="{% url "main:index" %}">Homepage</a></li>
                                    <li><a href="{% url "main:explore" %}">Explore</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="#">Pages<span></span></a>
                                <ul>
                                    <li><a href="{% url "articles:articles" %}">Articles</a></li>
                                </ul>
                            </li>
                        </ul>
                        <div class="menu_side_area">
                            {% if not user.is_authenticated %}
                            <a href="{% url "users:login" %}" class="btn-main btn-wallet"><i class="icon_wallet_alt"></i><span>Log in</span></a>
                            <span id="menu-btn"></span>
                            {% else %}
                            <div class="de-login-menu">
                                <a href="{% url "profiling:create_options" %}" class="btn-main"><i class="fa fa-plus"></i><span>Create</span></a>


                                <a href="{% url "users:wallet" %}" class="btn-main">
                                    Wallet
                                 </a>

                    

                                <span id="de-click-menu-notification" class="de-menu-notification">
                                    <div id="nCounter">
                                    <span class="d-count" id="eventsCount"></span>
                                    </div>
                                    <i class="fa fa-bell"></i>
                                </span>

                                <span id="de-click-menu-profile" class="de-menu-profile">                           
                                    <img src="{{ user.avatar.url }}" class="img-fluid" alt="">
                                </span>

                                <div id="de-submenu-notification" class="de-submenu">
                                    <div class="de-flex">
                                        <div><h4>Notifications</h4></div>
                                        <a href="#" id="clearNotifications">Clear</a>
                                    </div>

                                    <ul>
                                        <div id="eventContainer">
                                        {% comment %} JavaScript Events {% endcomment %}
                                        </div>

                                    </ul>
                                </div>

                                <div id="de-submenu-profile" class="de-submenu">
                                    <div class="d-name">
                                        <h4>{{ user.first_name }}</h4>
                                        <a href="{% url "users:edit_profile" %}">Set display name</a>
                                    </div>
                                    <div class="spacer-10"></div>
                                    <div class="d-balance">
                                        <h4>Balance</h4>
                                        {{ user.balance }} ETH
                                    </div>
                                    <div class="spacer-10"></div>
                                    <div class="d-wallet">
                                        <h4>My Wallet</h4>
                                        <span id="wallet" class="d-wallet-address">DdzFFzCqrhshMSxb9oW3mRo4MJrQkusV3fGFSTwaiu4wPBqMryA9DYVJCkW9n7twCffG5f5wX2sSkoDXGiZB1HPa7K7f865Kk4LqnrME</span>
                                        <button id="btn_copy" title="Copy Text">Copy</button>
                                    </div>

                                    <div class="d-line"></div>

                                    <ul class="de-submenu-profile">
                                        {% if user.is_admin or user.is_staff %}
                                        <li><a href="{% url 'admin:index' %}"><i class="fa  fa-user-secret"></i> Admin</a>
                                        {% endif %}
                                        <li><a href="{% url "users:profile" user.username %}"><i class="fa fa-user"></i> My profile</a>
                                        <li><a href="{% url "users:edit_profile" %}"><i class="fa fa-pencil"></i> Edit profile</a>
                                        <li><a href="{% url "users:logout" %}"><i class="fa fa-sign-out"></i> Log out</a>
                                    </ul>
                                </div>
                                {% if messages %}<span>{{ message }}</span>{% else %}{% endif %}
                                <span id="menu-btn"></span>
                            </div>

                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</header>

marketplace/templates/includes/messages.html
{% if messages %}
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
    </symbol>
    <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
    </symbol>
</svg>
{% for msg in messages %}
{% if msg.tags == "success" %}
    <div class="alert alert-success d-flex align-items-center" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
            <div>
            {{ msg }}
            </div>
    </div>
{% else %}
    <div class="alert alert-warning d-flex align-items-center" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:"><use xlink:href="#exclamation-triangle-fill"/></svg>
            <div>
            {{ msg }}
            </div>
    </div>
{% endif %}
{% endfor %}
{% endif %}

marketplace/templates/includes/subheader.html
{% load static %}
<section id="subheader" class="text-light" data-bgimage="url({% static "images/background/subheader.jpg" %}) top">
    <div class="center-y relative text-center">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h1>{{ subtitle }}</h1>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</section>