marketplace/articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.articles, name='articles'),
    path('search/', views.articles, name='search'),
    path('<int:article_id>/', views.article_detail, name='article_detail'),
    path('write/', views.write_article, name='write_article'),
]

marketplace/main/urls.py
from django.urls import include, path
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'item', views.ItemViewSet)
router.register(r'events', views.EventsViewSet)

app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('like/', views.like, name='like'),
    path('explore/', views.explore, name='explore'),
    path('api/', include(router.urls)),
]

marketplace/marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('', include('main.urls', namespace='main')),
    path('p/', include('profiling.urls', namespace='profiling')),
    path('user/', include('users.urls', namespace='users')),
    path('articles/', include('articles.urls', namespace='articles'))
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('wallet/', views.wallet, name='wallet'),
    path('<slug:author_username>/', views.profile, name='profile'),

]

marketplace/articles/models.py
from django.db import models
from users.models import User


class Post(models.Model):
    title = models.CharField(max_length=113, verbose_name="Title")
    text = models.TextField(verbose_name="Text")
    highlighted_text = models.TextField(
        verbose_name="Highlighted Text", blank=True, null=True
    )
    is_published = models.BooleanField("Is published", default=True)
    image = models.ImageField(
        upload_to="post_image", default="post_image/default.jpg"
    )
    pub_date = models.DateTimeField(
        verbose_name="Publishing date", auto_now_add=True
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="Article author"
    )
    category = models.ForeignKey(
        "Categories",
        on_delete=models.CASCADE,
        default=None,
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "Article"
        verbose_name_plural = "Articles"

    def __str__(self):
        return self.title


class Categories(models.Model):
    category_name = models.CharField("Category", max_length=50)
    slug = models.CharField("slug", max_length=50)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.category_name

marketplace/articles/forms.py
from django import forms


from .models import Post


class ArticleCreationForm(forms.ModelForm):
    image = forms.ImageField(required=False)
    title = forms.CharField()
    text = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Post
        fields = ("image", "title", "text")
        exclude = ('author', 'category')

marketplace/articles/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.core.paginator import Paginator
from django.urls import reverse
from django.utils import timezone

from .utils import q_search
from .models import Post, Categories
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import ArticleCreationForm


def articles(request):
    template = "articles/articles.html"
    page = request.GET.get("page", 1)
    filter_category = request.GET.get("category", None)
    query = request.GET.get("q", None)

    if filter_category:
        posts = (
            Post.objects.select_related("category")
            .filter(is_published=True, category__slug=filter_category)
            .order_by("-pub_date")
        )
    elif query:
        posts = q_search(query)
    else:
        posts = (
            Post.objects.select_related("category")
            .filter(is_published=True)
            .order_by("-pub_date")
        )

    paginator = Paginator(posts, per_page=6)
    current_page = paginator.page(page)

    context = {
        "posts": current_page,
        "subtitle": "Articles",
        "dark": True,
    }
    return render(request, template, context)


def article_detail(request, article_id):
    template = "articles/article-detail.html"
    post_details = Post.objects.select_related("author").get(pk=article_id)
    context = {"post": post_details, "subtitle": post_details.title, "dark": True}
    return render(request, template, context)


@login_required
def write_article(request):
    template = "articles/write-article.html"

    categories = Categories.objects.all()

    if request.method == "POST":
        form = ArticleCreationForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            category_name = request.POST["category"]
            category = Categories.objects.get(category_name=category_name)
            post.category = category
            post.save()
            messages.success(request, "Article successfully created!")
            return HttpResponseRedirect(reverse("articles:articles"))
        else:
            errors = {
                "Title": request.POST["title"],
                "Text": request.POST["text"],
                "Category": request.POST["category"],
            }
            errors = [err[0] for err in errors.items() if not err[1]]
            messages.error(
                request,
                f"Please, do not leave required fields blank -> {', '.join(errors)}",
            )

    else:
        form = ArticleCreationForm()

    date = timezone.now()
    context = {
        "categories": categories,
        "subtitle": "Write your article",
        "date": date,
        "dark": True,
    }
    return render(request, template, context)

marketplace/templates/articles/article-detail.html
{% extends "base.html" %}
{% load static %}
{% load posts_tags %}

{% block title %}
Gigaland - {{ post.title }}
{% endblock %}

{% block content %}    
{% include "includes/subheader.html" %}

            <!-- section begin -->
			<section aria-label="section">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="blog-read">

                                <img alt="" src="{{ post.image.url }}" class="img-fullwidth rounded">

                                <div class="post-text">
                                    <p style="font-size: 19px; color: black;">{{ post.text }}</p>
                                    
                                    <blockquote>{{ post.highlighted_text }}</blockquote>

                                    

                                    <span class="post-date">{{ post.pub_date|date:"E d Y" }}</span>
                                    <span class="post-comment">1</span>
                                    <span class="post-like">181</span>

                                </div>

                            </div>

                            <div class="spacer-single"></div>

                            <div id="blog-comment">
                                <h4>Comments (5)</h4>

                                <div class="spacer-half"></div>

                                <ol>
                                    <li>
                                        <div class="avatar">
                                            <img src="images/misc/avatar-2.jpg" alt="" /></div>
                                        <div class="comment-info">
                                            <span class="c_name">John Smith</span>
                                            <span class="c_date id-color">15 January 2020</span>
                                            <span class="c_reply"><a href="#">Reply</a></span>
                                            <div class="clearfix"></div>
                                        </div>

                                        <div class="comment">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</div>
                                        <ol>
                                            <li>
                                                <div class="avatar">
                                                    <img src="images/misc/avatar-2.jpg" alt="" /></div>
                                                <div class="comment-info">
                                                    <span class="c_name">John Smith</span>
                                                    <span class="c_date id-color">15 January 2020</span>
                                                    <span class="c_reply"><a href="#">Reply</a></span>
                                                    <div class="clearfix"></div>
                                                </div>
                                                <div class="comment">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt
                                                    explicabo.</div>
                                            </li>
                                        </ol>
                                    </li>

                                    <li>
                                        <div class="avatar">
                                            <img src="images/misc/avatar-2.jpg" alt="" /></div>
                                        <div class="comment-info">
                                            <span class="c_name">John Smith</span>
                                            <span class="c_date id-color">15 January 2020</span>
                                            <span class="c_reply"><a href="#">Reply</a></span>
                                            <div class="clearfix"></div>
                                        </div>
                                        <div class="comment">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</div>
                                        <ol>
                                            <li>
                                                <div class="avatar">
                                                    <img src="images/misc/avatar-2.jpg" alt="" /></div>
                                                <div class="comment-info">
                                                    <span class="c_name">John Smith</span>
                                                    <span class="c_date id-color">15 January 2020</span>
                                                    <span class="c_reply"><a href="#">Reply</a></span>
                                                    <div class="clearfix"></div>
                                                </div>
                                                <div class="comment">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt
                                                    explicabo.</div>
                                            </li>
                                        </ol>
                                    </li>

                                    <li>
                                        <div class="avatar">
                                            <img src="images/misc/avatar-2.jpg" alt="" /></div>
                                        <div class="comment-info">
                                            <span class="c_name">John Smith</span>
                                            <span class="c_date id-color">15 January 2020</span>
                                            <span class="c_reply"><a href="#">Reply</a></span>

                                            <div class="clearfix"></div>
                                        </div>
                                        <div class="comment">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</div>
                                    </li>
                                </ol>

                                <div class="spacer-single"></div>

                                <div id="comment-form-wrapper">
                                    <h4>Leave a Comment</h4>
                                    <div class="comment_form_holder">
                                        <form id="contact_form" name="form1" class="form-border" method="post" action="#">

                                            <label>Name</label>
                                            <input type="text" name="name" id="name" class="form-control" />

                                            <label>Email <span class="req">*</span></label>
                                            <input type="text" name="email" id="email" class="form-control" />
                                            <div id="error_email" class="error">Please check your email</div>

                                            <label>Message <span class="req">*</span></label>
                                            <textarea cols="10" rows="10" name="message" id="message" class="form-control"></textarea>
                                            <div id="error_message" class="error">Please check your message</div>
                                            <div id="mail_success" class="success">Thank you. Your message has been sent.</div>
                                            <div id="mail_failed" class="error">Error, email not sent</div>

                                            <p id="btnsubmit">
                                                <input type="submit" id="send" value="Send" class="btn btn-main" /></p>



                                        </form>
                                    </div>
                                </div>
                            </div>

                        </div>

                        <div id="sidebar" class="col-md-4">
                            <div class="widget widget-post">
                                <h4>Recent Posts</h4>
                                <div class="small-border"></div>
                                <ul>									
                                    <li><span class="date">10 Jun</span><a href="#">6 Make Mobile Website Faster</a></li>
                                    <li><span class="date">22 Jun</span><a href="#">Experts Web Design Tips</a></li>
                                    <li><span class="date">20 Jun</span><a href="#">Importance Of Web Design</a></li>
                                    <li><span class="date">12 Jun</span><a href="#">Avoid These Erros In UI Design</a></li>

                                </ul>
                            </div>

                            <div class="widget widget-text">
                                <h4>Author</h4>
                                <div class="small-border"></div>
                                <span class="profile_username"><a href="{% url "users:profile" post.author.username %}">@{{ post.author }}</a></span>
                            </div>
                            <div class="widget widget_tags">
                                <h4>Category</h4>
                                <div class="small-border"></div>
                                <ul>
                                    <li><a href="{% url "articles:articles" %}?category={{ post.category.slug }}" style="font-size: 90%;">{{ post.category}}</a></li>
                                </ul>
                            </div>

                        </div>
                    </div>
                </div>
            </section>
{% endblock content %}

marketplace/templates/articles/articles.html
{% extends "base.html" %}
{% load static %}
{% load posts_tags %}

{% block title %}
Gigaland - Articles
{% endblock %}

{% block content %}
            
            <!-- section begin -->
            {% include "includes/subheader.html" %}
            <!-- section close -->
            
            <!-- section begin -->
			<section aria-label="section">
                <div class="container">
                    {% include "includes/messages.html" %}
                    <div class="row">

                        <div class="col-lg-12">
                            <div style="float: right; right: 0px;">
                                <a href="{% url "articles:write_article" %}" class="btn-main"><i class="fa fa-plus"></i><span> Write your article</span></a>
                            </div>

                            <div class="items_filter">
                                <form action="{% url "articles:search" %}" class="row form-dark" id="form_quick_search" method="get" name="form_quick_search" role="search">
                                    <div class="col text-center">
                                        <input class="form-control" id="name_1" name="q" placeholder="search article here..." type="text" />
                                        <a href="" id="btn-submit"><i class="fa fa-search bg-color-secondary"></i></a>
                                        <div class="clearfix"></div>
                                    </div>
                                </form>
                                
                                {% if request.GET.category %}
                                <div class="col text-center">
                                    <a href="{% url "articles:articles" %}">Reset filters</a>
                                </div>
                                {% endif %}
                                
                                {% comment %} For better times {% endcomment %}
                                {% comment %} <div id="item_category" class="dropdown">
                                    <a href="#" class="btn-selector">All categories</a>
                                    <ul>
                                        <li class="active"><span><a href="?">All categories</a></span></li>
                                        {% for category in categories %}
                                        <li><span>{{ category }}</span></li>
                                        {% endfor %}
                                    </ul>
                                </div> {% endcomment %}
                                


                            </div>
                            
                        </div>
        
                        {% if posts %}
                        {% for post in posts %}
						<div class="col-lg-4 col-md-6 mb30">
							<div class="bloglist item">
                                    <div class="post-content">
                                        <div class="post-image">
                                            <a href="{% url "articles:article_detail" post.id %}"><img alt="" src="{{ post.image.url }}" class="lazy"></a>
                                        </div>
                                        <div class="post-text">
                                            <span class="p-tagline">{{ post.category }}</span>
                                            <span class="p-date">{{ post.pub_date|date:"E d Y" }}</span>
                                            <h4><a href="{% url "articles:article_detail" post.id %}">
                                            {% autoescape off %}
                                            {% if post.headline %}{{ post.headline }}{% else %}{{ post.title }}{% endif %}<span></span></a></h4>
                                            <p>{% if post.bodyline %}{{ post.bodyline|truncatewords:22 }}{% else %}{{ post.text|truncatewords:22 }}{% endif %}</p>
                                            {% endautoescape %}
                                        </div>
                                    </div>
                                </div>
						</div>
						{% endfor %}
                        {% else %}

                        <div class="col text-center">
                            <a href="{% url "articles:articles" %}" style="font-size: 200%;">Not found</a>
                        </div>

                        {% endif %}
                        

                        <div class="spacer-single"></div>
                        
                        {% if posts.paginator.num_pages > 1 %}
                        <ul class="pagination">

                            {% comment %} "Previous" button {% endcomment %}
                            {% if posts.has_previous %}
                                <li><a style="color: #8364e2; font-weight: bold;" href="?page={{posts.previous_page_number}}">Prev</a></li>
                            {% else %}
                                <li><a>Prev</a></li>
                            {% endif %}

                            {% comment %} Button "1" {% endcomment %}
                            {% if posts.number == 1 %}
                                <li class="active"><a>
                            {% else %}
                                <li><a href="?{% change_params page=1 %}">
                            {% endif %}
                                1</a></li>
                            {% if posts.number > 4 %}
                                <li><a>...</li></a>
                            {% endif %}

                            {% comment %} Pages cycle (2 > current > 2) {% endcomment %}
                            {% for page in posts.paginator.page_range %}
                            {% if posts.number >= posts.paginator.num_pages|add:-3 %}{% endif %}
                            {% if page >= posts.number|add:-2 and page <= posts.number|add:2 and page != 1 %}
                            {% if posts.number == page %}
                                <li class="active"><a>
                            {% else %}
                                <li><a href="?{% change_params page=page %}">
                            {% endif %}
                                {{ page }}</a></li>
                            {% endif %}
                            {% endfor %}

                            {% comment %} Button "Last page" {% endcomment %}
                            {% if posts.number < posts.paginator.num_pages|add:-3 %}
                                <li><a>...</li></a>
                                <li><a href="?page={{ posts.paginator.num_pages }}">{{ posts.paginator.num_pages }}</a></li>
                            {% endif %}
                            {% if posts.number == posts.paginator.num_pages|add:-3 %}
                                <li><a href="?{% change_params page=posts.paginator.num_pages %} ">{{ posts.paginator.num_pages }}</a></li>
                            {% endif %}

                            {% comment %} "Next" button {% endcomment %}
                            {% if posts.has_next %}
                            <li><a style="color: #8364e2; font-weight: bold;" href="?{% change_params page=posts.next_page_number %}">Next</a></li>
                            {% else %}
                            <li><a>Next</a></li>
                            {% endif %}

                        </ul>
                        {% endif %}                        
                        

                    </div>
                </div>
            </section>

{% endblock content %}

marketplace/templates/articles/write-article.html
{% extends "base.html" %}
{% load static %}
{% load posts_tags %}

{% block title %}
Gigaland - Articles
{% endblock %}

{% block content %}
            
            <!-- section begin -->
            {% include "includes/subheader.html" %}
            <!-- section close -->
            

            <!-- section begin -->
            <section aria-label="section">
                <div class="container">
                    <div class="row wow fadeIn">
                        <div class="col-lg-7 offset-lg-1">
                            <form action="" id="form-create-item" class="form-border" method="post" enctype="multipart/form-data">
                                {% csrf_token %}

                                {% include "includes/messages.html" %}

                                <div class="field-set">
                                    <h5>Article image</h5>

                                    <div class="d-create-file">
                                        <p id="file_name">PNG, JPG Max 200mb. 16:10 Recomended</p>
                                        <label for="id_image"><input type="button" id="get_file" class="btn-main" value="Browse" onclick="triggerFileInput()"></label>
                                        <input type="file" id="id_image" name="image" style="display: none;" accept="image/*" onchange="previewImageArticle()">
                                    </div>

                                    <div class="spacer-40"></div>
                                    <h5>Title</h5>
                                    <input type="text" name="title" id="id_title" class="form-control" maxlength="113" placeholder="e.g. 'Best way to make money from NFT'" value="{% if form.title.value %}{{ form.title.value }}{% endif %}" />

                                    <div class="spacer-20"></div>

                                    <h5>Text</h5>
                                    <textarea data-autoresize name="text" id="id_text" class="form-control" placeholder="e.g. 'This is very secret information..'" value="{% if form.text.value %}{{ form.text.value }}{% endif %}"></textarea>

                                    <div class="spacer-20"></div>

                                    <h5>Choose category</h5>
                                    <p class="p-info">This will make it easier to find your article</p>

                                    <div id="item_collection" class="dropdown fullwidth mb20">
                                        <a href="#" class="btn-selector" id="collectionDropdownBtn">Select Category</a>
                                        <ul>
                                            {% for category in categories %}
                                            <li data-value="{{ category }}"><span>{{ category }}</span></li>
                                            {% endfor %}
                                        </ul>
                                        <input type="hidden" id="id_category" name="category">
                                    </div>

                                    <div class="spacer-20"></div>


                                    <div class="spacer-single"></div>

                                    <input type="submit" id="submit" class="btn-main" value="Post">
                                    <div class="spacer-single"></div>
                                </div>
                            </form>
                        </div>

                        
                            <div class="col-lg-4 col-md-6 mb30">
                                <h5>Preview:</h5>
                                <div class="bloglist item">
                                        <div class="post-content">
                                            <div class="post-image">
                                               <img alt="" src="{% static "images/posts/news-5.jpg" %}" class="lazy">
                                            </div>
                                            <div class="post-text">
                                                <span class="p-tagline" id="category_display">category</span>
                                                <span class="p-date">{{ date|date:"E d Y" }}</span>
                                                <h4 id="title_display">Title<span></span></h4>
                                                <p id="text_display">Text</p>
                                            </div>
                                        </div>
                                    </div>
                            </div>
                                                                
                    </div>
                </div>
            </section>

{% endblock content %}