marketplace/main/urls.py
from django.urls import include, path
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'item', views.ItemViewSet)
router.register(r'events', views.EventsViewSet)

app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('like/', views.like, name='like'),
    path('explore/', views.explore, name='explore'),
    path('api/', include(router.urls)),
]

marketplace/marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('', include('main.urls', namespace='main')),
    path('p/', include('profiling.urls', namespace='profiling')),
    path('user/', include('users.urls', namespace='users')),
    path('articles/', include('articles.urls', namespace='articles'))
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/profiling/urls.py
from django.urls import path

from . import views

app_name = 'profiling'

urlpatterns = [
    path('collection/<slug:collection_slug>/', views.collection, name='collection'),
    path('item/<int:id>/', views.item, name='item'),


    path('create/', views.create_options, name='create_options'),
    path('create/single/', views.create_single, name='create_single'),

    path('edit/item<int:id>/', views.edit_item, name='edit_item'),
    path('edit/delete<int:id>/', views.delete_item, name='delete_item')
]

marketplace/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('wallet/', views.wallet, name='wallet'),
    path('<slug:author_username>/', views.profile, name='profile'),

]

marketplace/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class User(AbstractUser):
    avatar = models.ImageField(
        upload_to="user_avatar", default="user_avatar/default.jpg"
    )
    banner = models.ImageField(
        upload_to="user_banner", default="user_banner/default.jpg"
    )
    balance = models.DecimalField(
        "balance", default=0.00, max_digits=4, decimal_places=2
    )

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"

    def get_absolute_url(self):
        return reverse("users:profile", args=[self.username])

    def __str__(self):
        return self.username

marketplace/users/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm,
    UsernameField,
    UserCreationForm,
    UserChangeForm
)

from .models import User


class UserLoginForm(AuthenticationForm):
    username = UsernameField(
        label="",
    )
    password = forms.CharField(
        label="",
    )
    error_messages = {
        "invalid_login": ("Please enter a correct username and password."),
        "inactive": ("This account is inactive."),
    }

    class Meta:
        model = User


class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(required=False)
    username = UsernameField()
    email = forms.CharField()

    class Meta:
        model = User
        fields = ("first_name", "username", "email", "password2")


class UserEditProfile(UserChangeForm):
    avatar = forms.ImageField(required=False)
    banner = forms.ImageField(required=False)
    first_name = forms.CharField(required=False)
    username = UsernameField()
    email = forms.CharField()

    class Meta:
        model = User
        fields = (
            'avatar',
            'banner',
            'first_name',
            'username',
            'email',
        )


class BalanceTopUpForm(forms.Form):
    balance = forms.DecimalField()

    class Meta:
        fields = ('balance',)

    def clean_balance(self):
        data = self.cleaned_data["balance"]

        if data <= 0:
            raise forms.ValidationError("Incorrect number")
        return data

marketplace/users/views.py
from django.forms import ValidationError
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse

from main.models import Events
from main.utils import add_user_action_event, add_user_transaction_event
from profiling.models import Item

from .forms import (
    BalanceTopUpForm,
    UserEditProfile,
    UserLoginForm,
    UserRegisterForm,
)
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required

from .models import User
from profiling.utils import error_messages


def profile(request, author_username):
    template = "users/author.html"
    author_info = User.objects.get(username=author_username)
    item_info_owner = Item.objects.filter(owner=author_info.id)
    item_info_creator = Item.objects.filter(creator=author_info.id)
    context = {
        "author_info": author_info,
        "item_info_owner": item_info_owner,
        "item_info_creator": item_info_creator,
        "dark": False,
    }
    return render(request, template, context)


@login_required
def edit_profile(request):
    template = "users/edit-profile.html"
    if request.method == "POST":
        form = UserEditProfile(
            data=request.POST, instance=request.user, files=request.FILES
        )
        if form.is_valid():
            form.save()
            messages.success(request, "Changes successfully applied!")

            add_user_action_event("edit profile", request.user)

            return HttpResponseRedirect(reverse("users:edit_profile"))

        else:
            error_messages(request, "username", "email")
    else:
        form = UserEditProfile(instance=request.user)
    context = {"form": form, "dark": True, "subtitle": "Edit Profile"}
    return render(request, template, context)


@login_required
def wallet(request):
    template = "users/wallet.html"

    if request.method == "POST":
        user = request.user
        form = BalanceTopUpForm(data=request.POST)
        if form.is_valid():
            money = form.cleaned_data["balance"]
            if money <= 0:
                raise ValidationError("Incorrect number")
            user.balance += money
            user.save()
            add_user_transaction_event(
                event="top up balance", user=request.user, number=money
            )
            messages.success(request, "Balance successfully changed!")

            return HttpResponseRedirect(reverse("users:wallet"))
        else:
            error_messages(request, "balance")
    else:
        form = BalanceTopUpForm()

    context = {
        "subtitle": "Wallet",
        "dark": True,
    }
    return render(request, template, context)


def register(request):
    template = "users/register.html"
    if request.method == "POST":
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance

            session_key = request.session.session_key

            auth.login(request, user)

            if session_key:
                Events.objects.filter(session_key=session_key).update(
                    user=user, session_key=None
                )

            add_user_action_event("register", user)

            return HttpResponseRedirect(reverse("main:index"))
    else:
        form = UserRegisterForm()

    context = {
        "form": form,
        "dark": True,
        "subtitle": "Sign in",
    }
    return render(request, template, context)


def login(request):
    template = "users/login.html"

    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password"]
            user = auth.authenticate(
                request, username=username, password=password
            )

            session_key = request.session.session_key

            if user:
                auth.login(request, user)

                if session_key:
                    Events.objects.filter(session_key=session_key).update(
                        user=user, session_key=None
                    )

                add_user_action_event("login", user)

                redirect_page = request.POST.get("next", None)
                if redirect_page and redirect_page != reverse("users:logout"):
                    return HttpResponseRedirect(request.POST.get("next"))
                else:
                    return HttpResponseRedirect(reverse("main:index"))
    else:
        form = UserLoginForm()

    context = {"form": form, "dark": True}
    return render(request, template, context)


@login_required
def logout(request):
    add_user_action_event("logout", request.user)
    auth.logout(request)
    return redirect(reverse("main:index"))

marketplace/templates/users/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Gigaland - Log in
{% endblock %}
{% block content %}
			<section class="full-height relative no-top no-bottom vertical-center" data-bgimage="url({% static "images/background/subheader.jpg" %}) top" data-stellar-background-ratio=".5">
                <div class="overlay-gradient t50">
					<div class="center-y relative">
						<div class="container">
							<div class="row align-items-center">
								<div class="col-lg-5 text-light wow fadeInRight" data-wow-delay=".5s">
                                <div class="spacer-10"></div>
                                <h1>Create, sell or collect digital items.</h1>
                                <p class="lead"></p>
                            </div>
								
								<div class="col-lg-4 offset-lg-2 wow fadeIn" data-wow-delay=".5s">
									<div class="box-rounded padding40" data-bgcolor="#ffffff">
										<h3 class="mb10">Log in</h3>
										<p>Or create a new account <a href="{% url "users:register" %}">here<span></span></a>.</p>
										<form action="{% url "users:login" %}" method="post" name="contactForm" id='contact_form' class="form-border" >

											{% csrf_token %}
											
											{% if request.GET.next %}
												<input type="hidden" name="next" value={{ request.GET.next }}>
											{% endif %}
											
											{% if form.non_field_errors %}
											<span style="font-size: 95%; font-style: italic; color: red; opacity: 0.85;">{{ form.error_messages.invalid_login }}</span>
											{% endif %}

											<div class="field-set">
                                                <input type='text' name='username' id='id_username' value="{% if form.username.value %}{{ form.username.value }}{% endif %}" class="form-control" placeholder="username" autocomplete="username" required>
                                            </div>
											
											 <div class="field-set">
                                                <input type='password' name='password' id='id_password' class="form-control" placeholder="password" autocomplete="current-password" required>
                                            </div>

											<p>Forgot your password? <a href="">Click here</a><span></span>.</p>

											<div class="field-set">
												<input type='submit' value='Submit' class="btn btn-main btn-fullwidth color-2" >
											</div>
											
											<div class="clearfix"></div>
											
											<div class="spacer-single"></div>

                                        <!-- social icons -->
                                        <ul class="list s3">
                                            <li>Continue with:</li>
                                            <li><a href="#">Facebook</a></li>
                                            <li><a href="#">Google</a></li>
                                        </ul>
                                        <!-- social icons close -->
                                </form>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>		
            
        </div>
{% endblock %}

marketplace/templates/users/register-old.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Gigaland - Sign in
{% endblock %}
{% block content %}
            <!-- section begin -->
            {% include "includes/subheader.html" %}
            <!-- section close -->
            
            <section aria-label="section">
                <div class="container">
					<div class="row">
						<div class="col-md-8 offset-md-2">
							<h3>Don't have an account? Register now.</h3>
                            <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
							
							<div class="spacer-10"></div>
							
							<form action="{% url "users:register" %}" name="contactForm" id='contact_form' class="form-border" method="post" >

                                {% csrf_token %}

                                <div class="row">

                                    <div class="col-md-6">
                                        <div class="field-set">
                                            <label for="id_first_name">Name:</label>
                                            <input type='text' name='first_name' id='id_first_name' class="form-control"
                                            value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}" required>
                                        </div>
                                    </div>

                                    <div class="col-md-6">
                                        <div class="field-set">
                                            <label for="id_username">Choose a Username:</label>
                                            <input type='text' name='username' id='id_username' class="form-control"
                                            value="{% if form.username.value %}{{ form.username.value }}{% endif %}" required>
                                            {% if form.username.errors %}
                                            <span style="font-size: 95%; font-style: italic; color: red; opacity: 0.85;">{{ form.username.errors }}</span>
                                            {% endif %}
                                        </div>
                                    </div>

                                    <div class="col-md-6">
                                        <div class="field-set">
                                            <label for="id_email">Email Address:</label>
                                            <input type='text' name='email' id='id_email' class="form-control"
                                            value="{% if form.email.value %}{{ form.email.value }}{% endif %}" autocomplete="email" required>
                                            {% if form.email.errors %}
                                            <span style="font-size: 95%; font-style: italic; color: red; opacity: 0.85;">{{ form.email.errors }}</span>
                                            {% endif %}
                                        </div>
                                    </div>

                                    <div class="col-md-6">
                                        <div class="field-set">
                                            <label for="id_password1">Password:</label>
                                            <input type='password' name='password1' id='id_password1' class="form-control" autocomplete="new-password">
                                            <label for="id_password2">Confirm Password:</label>
                                            <input type='password' name='password2' id='id_password2' class="form-control" autocomplete="new-password">
                                            {% if form.password2.errors %}
                                            <span style="font-size: 95%; font-style: italic; color: red; opacity: 0.85;">{{ form.password2.errors }}</span>
                                            {% endif %}
                                        </div>
                                    </div>

                                    <div class="col-md-12">

                                        <div id='submit' class="pull-left">
                                            <input type='submit' class="btn btn-main color-2">
                                        </div>

                                        <div id='mail_success' class='success'>Your message has been sent successfully.</div>
                                        <div id='mail_fail' class='error'>Sorry, error occured this time sending your message.</div>
                                        <div class="clearfix"></div>

                                    </div>

                                </div>
                            </form>
							
						</div>
                    </div>
				</div>
            </section>
			
			
        </div>
{% endblock %}

marketplace/templates/users/register.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Gigaland - Sign in
{% endblock %}
{% block content %}
			<section class="full-height relative no-top no-bottom vertical-center" data-bgimage="url({% static "images/background/subheader.jpg" %}) top" data-stellar-background-ratio=".5">
                <div class="overlay-gradient t50">
					<div class="center-y relative">
						<div class="container">
							<div class="row align-items-center">
								<div class="col-lg-5 text-light wow fadeInRight" data-wow-delay=".5s">
                                <div class="spacer-10"></div>
                                <h1>Become part of a wonderful new world!</h1>
                                <p class="lead"></p>
                            </div>
								
								<div class="col-lg-4 offset-lg-2 wow fadeIn" data-wow-delay=".5s">
									<div class="box-rounded padding40" data-bgcolor="#ffffff">
										<h3 class="mb10">Sign in</h3>
										<p><span></span></a></p>
										<form action="{% url "users:register" %}" name="contactForm" id='contact_form' class="form-border" method="post" >

											{% csrf_token %}
											
	

											<div class="field-set">
												<input type='text' name='first_name' id='id_first_name' class="form-control"
												value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}" placeholder="name" required>
											</div>
											
											<div class="field-set">
												<input type='text' name='username' id='id_username' class="form-control"
												value="{% if form.username.value %}{{ form.username.value }}{% endif %}" placeholder="username" required>
												{% if form.username.errors %}
												<span style="font-size: 95%; font-style: italic; color: red; opacity: 0.85;">{{ form.username.errors }}</span>
												{% endif %}
											</div>

											<div class="field-set">
												<input type='text' name='email' id='id_email' class="form-control"
												value="{% if form.email.value %}{{ form.email.value }}{% endif %}" autocomplete="email" placeholder="email" required>
												{% if form.email.errors %}
												<span style="font-size: 95%; font-style: italic; color: red; opacity: 0.85;">{{ form.email.errors }}</span>
												{% endif %}
											</div>
											
											 <div class="field-set">
                                                <input type='password' name='password1' id='id_password1' class="form-control" placeholder="password" required>
                                            </div>

											<div class="field-set">
                                                <input type='password' name='password2' id='id_password2' class="form-control" placeholder="confirm password" required>
												{% if form.password2.errors %}
												<span style="font-size: 95%; font-style: italic; color: red; opacity: 0.85;">{{ form.password2.errors }}</span>
												{% endif %}
                                            </div>



											{% comment %} <div class="field-set">
                                                {{ form.username }}
                                            </div>
											
											 <div class="field-set">
                                                {{ form.password }}
                                            </div>
											 {% endcomment %}

											<div class="field-set">
												<input type='submit' value='Submit' class="btn btn-main btn-fullwidth color-2" >
											</div>
											
											<div class="clearfix"></div>
											
											<div class="spacer-single"></div>

                                        <!-- social icons -->
                                        <ul class="list s3">
                                            <li>Continue with:</li>
                                            <li><a href="#">Facebook</a></li>
                                            <li><a href="#">Google</a></li>
                                        </ul>
                                        <!-- social icons close -->
                                </form>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>		
            
        </div>
{% endblock %}

marketplace/templates/users/wallet.html
{% extends "base.html" %}
{% load static %}
{% load posts_tags %}

{% block title %}
Gigaland - Edit item {{ item.title }}
{% endblock %}

{% block content %}
            
            <!-- section begin -->
            {% include "includes/subheader.html" %}
            <!-- section close -->            

            <!-- section begin -->
			<section aria-label="section">
                <div class="container">
                    {% include "includes/messages.html" %}
                    <div class="row">
                        <div class="col-lg-3 mb30">
                            <a href="#" class="box-url" data-bs-toggle="modal" data-bs-target="#my_wallet">
                                <span class="box-url-label">Most Popular</span>
                                <img src="{% static "images/wallet/1.png" %}" alt="" class="mb20">
                                <h4>Metamask</h4>
                                <p>Start exploring blockchain applications in seconds.  Trusted by over 1 million users worldwide.</p>
                            </a>
                        </div>

                        <div class="col-lg-3 mb30">
                            <a href="#" class="box-url" data-bs-toggle="modal" data-bs-target="#my_wallet">
                                <img src="{% static "images/wallet/2.png" %}" alt="" class="mb20">
                                <h4>Bitski</h4>
                                <p>Bitski connects communities, creators and brands through unique, ownable digital content.</p>
                            </a>
                        </div>       

                        <div class="col-lg-3 mb30">
                            <a href="#" class="box-url" data-bs-toggle="modal" data-bs-target="#my_wallet">
                                <img src="{% static "images/wallet/3.png" %}" alt="" class="mb20">
                                <h4>Fortmatic</h4>
                                <p>Let users access your Ethereum app from anywhere. No more browser extensions.</p>
                            </a>
                        </div>    

                        <div class="col-lg-3 mb30">
                            <a href="#" class="box-url" data-bs-toggle="modal" data-bs-target="#my_wallet">
                                <img src="{% static "images/wallet/4.png" %}" alt="" class="mb20">
                                <h4>WalletConnect</h4>
                                <p>Open source protocol for connecting decentralised applications to mobile wallets.</p>
                            </a>
                        </div>

                        <div class="col-lg-3 mb30">
                            <a href="#" class="box-url" data-bs-toggle="modal" data-bs-target="#my_wallet">
                                <img src="{% static "images/wallet/5.png" %}" alt="" class="mb20">
                                <h4>Coinbase Wallet</h4>
                                <p>The easiest and most secure crypto wallet. ... No Coinbase account required.
                                </p>
                            </a>
                        </div>

                        <div class="col-lg-3 mb30">
                            <a href="#" class="box-url" data-bs-toggle="modal" data-bs-target="#my_wallet">
                                <img src="{% static "images/wallet/6.png" %}" alt="" class="mb20">
                                <h4>Arkane</h4>
                                <p>Make it easy to create blockchain applications with secure wallets solutions.</p>
                            </a>
                        </div>       

                        <div class="col-lg-3 mb30">
                            <a href="#" class="box-url" data-bs-toggle="modal" data-bs-target="#my_wallet">
                                <img src="{% static "images/wallet/7.png" %}" alt="" class="mb20">
                                <h4>Authereum</h4>
                                <p>Your wallet where you want it. Log into your favorite dapps with Authereum.</p>
                            </a>
                        </div>    

                        <div class="col-lg-3 mb30">
                            <a href="#" class="box-url" data-bs-toggle="modal" data-bs-target="#my_wallet">
                                <span class="box-url-label">Most Simple</span>
                                <img src="{% static "images/wallet/8.png" %}" alt="" class="mb20">
                                <h4>Torus</h4>
                                <p>Open source protocol for connecting decentralised applications to mobile wallets.</p>
                            </a>
                        </div> 
                        
                        <!-- wallet -->
                        <div class="modal fade" id="my_wallet" tabindex="-1" aria-labelledby="buy_now" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered de-modal">
                              <div class="modal-content">
                                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                <div class="modal-body">
                                  <div class="p-3 form-border" style="text-align: center">
                                      <h3>Top up your balance</h3>
                                      <h6>Enter quantity of <span class="id-color-2">ETH</span></h6>
                                      <form method="post" action="{% url "users:wallet" %}">
                                        {% csrf_token %}
                                      <input type="text" name="balance" id="id_balance" class="form-control" value="" placeholder="ETH"/>
                                      <div class="spacer-single"></div>
                                      <input type="submit" name="submit" value="Recieve" class="btn-main"></input>
                                      </form>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                           <!-- wallet -->

                    </div>
                </div>
            </section>
{% endblock content %}